# Generated by Django 2.2 on 2018-12-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("Geo", "0007_longueurrue")]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                ("contact", models.CharField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catOne",
                    models.CharField(
                        blank=True,
                        choices=[("p", "Police"), ("g", "Gendarmerie")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "catTwo",
                    models.CharField(
                        blank=True,
                        choices=[("b", "Big"), ("s", "Small")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("geoHash", models.CharField(blank=True, max_length=200, null=True)),
                ("m2", models.IntegerField(blank=True, null=True)),
                ("m2_1", models.IntegerField(blank=True, null=True)),
                ("urlOffer", models.CharField(blank=True, max_length=500, null=True)),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "adresse",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="AdresseRent",
                        to="Geo.Adresse",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="SellerRent",
                        to="Offer.Seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catOne",
                    models.CharField(
                        blank=True,
                        choices=[("p", "Police"), ("g", "Gendarmerie")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "catTwo",
                    models.CharField(
                        blank=True,
                        choices=[("b", "Big"), ("s", "Small")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("geoHash", models.CharField(blank=True, max_length=200, null=True)),
                ("m2", models.IntegerField(blank=True, null=True)),
                ("m2_1", models.IntegerField(blank=True, null=True)),
                ("urlOffer", models.CharField(blank=True, max_length=500, null=True)),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "adresse",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="AdresseBuyPlan",
                        to="Geo.Adresse",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="SellerBuyPlan",
                        to="Offer.Seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Buy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catOne",
                    models.CharField(
                        blank=True,
                        choices=[("p", "Police"), ("g", "Gendarmerie")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "catTwo",
                    models.CharField(
                        blank=True,
                        choices=[("b", "Big"), ("s", "Small")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("geoHash", models.CharField(blank=True, max_length=200, null=True)),
                ("m2", models.IntegerField(blank=True, null=True)),
                ("m2_1", models.IntegerField(blank=True, null=True)),
                ("urlOffer", models.CharField(blank=True, max_length=500, null=True)),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "adresse",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="AdresseBuy",
                        to="Geo.Adresse",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="SellerBuy",
                        to="Offer.Seller",
                    ),
                ),
            ],
        ),
    ]
