# Generated by Django 2.1.5 on 2019-04-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpic',
            name='name',
            field=models.CharField(blank=True, choices=[('b', 'Big'), ('s', 'Small')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalpic',
            name='type',
            field=models.CharField(blank=True, choices=[('b', 'Big'), ('s', 'Small')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pic',
            name='name',
            field=models.CharField(blank=True, choices=[('b', 'Big'), ('s', 'Small')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pic',
            name='type',
            field=models.CharField(blank=True, choices=[('b', 'Big'), ('s', 'Small')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpic',
            name='value',
            field=models.TextField(blank=True, choices=[('b', 'Big'), ('s', 'Small')], null=True),
        ),
        migrations.AlterField(
            model_name='pic',
            name='value',
            field=models.TextField(blank=True, choices=[('b', 'Big'), ('s', 'Small')], null=True),
        ),
    ]
