# Generated by Django 2.2 on 2018-12-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("Geo", "0007_longueurrue"), ("Offer", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Equipement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[("b", "Big"), ("s", "Small")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "valeur",
                    models.CharField(
                        blank=True,
                        choices=[("b", "Big"), ("s", "Small")],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Norme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[("b", "Big"), ("s", "Small")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "valeur",
                    models.CharField(
                        blank=True,
                        choices=[("b", "Big"), ("s", "Small")],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valeur",
                    models.CharField(
                        blank=True,
                        choices=[("b", "Big"), ("s", "Small")],
                        max_length=300,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="buy",
            name="chambre",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buy",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="buy",
            name="piece",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buyplan",
            name="chambre",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buyplan",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="buyplan",
            name="piece",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rent",
            name="chambre",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rent",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="rent",
            name="piece",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="adresse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="AdresseSeller",
                to="Geo.Adresse",
            ),
        ),
        migrations.AddField(
            model_name="buy",
            name="equipement",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="EquipBuy", to="Offer.Equipement"
            ),
        ),
        migrations.AddField(
            model_name="buy",
            name="norme",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="NormeBuy", to="Offer.Norme"
            ),
        ),
        migrations.AddField(
            model_name="buy",
            name="pic",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="PicBuy", to="Offer.Pic"
            ),
        ),
        migrations.AddField(
            model_name="buyplan",
            name="equipement",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="EquipBuyPlan",
                to="Offer.Equipement",
            ),
        ),
        migrations.AddField(
            model_name="buyplan",
            name="norme",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="NormeBuyPlan", to="Offer.Norme"
            ),
        ),
        migrations.AddField(
            model_name="buyplan",
            name="pic",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="PicBuyPlan", to="Offer.Pic"
            ),
        ),
        migrations.AddField(
            model_name="rent",
            name="equipement",
            field=models.ManyToManyField(
                blank=True, related_name="EquipRent", to="Offer.Equipement"
            ),
        ),
        migrations.AddField(
            model_name="rent",
            name="norme",
            field=models.ManyToManyField(
                blank=True, related_name="NormeRent", to="Offer.Norme"
            ),
        ),
        migrations.AddField(
            model_name="rent",
            name="pic",
            field=models.ManyToManyField(
                blank=True, related_name="PicRent", to="Offer.Pic"
            ),
        ),
    ]
