# Generated by Django 2.2 on 2018-12-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("Offer", "0002_auto_20181227_1744")]

    operations = [
        migrations.AlterField(
            model_name="buy",
            name="equipement",
            field=models.ManyToManyField(
                blank=True, related_name="EquipBuy", to="Offer.Equipement"
            ),
        ),
        migrations.AlterField(
            model_name="buy",
            name="norme",
            field=models.ManyToManyField(
                blank=True, related_name="NormeBuy", to="Offer.Norme"
            ),
        ),
        migrations.AlterField(
            model_name="buy",
            name="pic",
            field=models.ManyToManyField(
                blank=True, related_name="PicBuy", to="Offer.Pic"
            ),
        ),
        migrations.AlterField(
            model_name="buyplan",
            name="equipement",
            field=models.ManyToManyField(
                blank=True, related_name="EquipBuyPlan", to="Offer.Equipement"
            ),
        ),
        migrations.AlterField(
            model_name="buyplan",
            name="norme",
            field=models.ManyToManyField(
                blank=True, related_name="NormeBuyPlan", to="Offer.Norme"
            ),
        ),
        migrations.AlterField(
            model_name="buyplan",
            name="pic",
            field=models.ManyToManyField(
                blank=True, related_name="PicBuyPlan", to="Offer.Pic"
            ),
        ),
    ]
