# Generated by Django 2.2 on 2018-12-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("Offer", "0003_auto_20181227_1745")]

    operations = [
        migrations.AddField(
            model_name="buy", name="available", field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name="buy",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buyplan",
            name="available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="buyplan",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rent",
            name="available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rent",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
