# Generated by Django 2.2 on 2018-12-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("Offer", "0004_auto_20181227_1757")]

    operations = [
        migrations.AddField(
            model_name="buy",
            name="ref1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="buy",
            name="ref2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="buy",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buyplan",
            name="ref1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="buyplan",
            name="ref2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="buyplan",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rent",
            name="ref1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="rent",
            name="ref2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="rent",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
