# Generated by Django 2.1.5 on 2019-04-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0004_auto_20190404_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='equipement',
            new_name='equipment',
        ),
    ]
