# Generated by Django 2.1.5 on 2019-04-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0005_auto_20190404_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='equipement',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='buyplan',
            old_name='equipement',
            new_name='equipment',
        ),
    ]
