# Generated by Django 2.2.2 on 2019-06-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0007_auto_20190405_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbuyplan',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbuyplan',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalequipment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalequipmentname',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalgroupseller',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalnorm',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalnorm',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalnormname',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpic',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrent',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrent',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='historicalseller',
            name='group',
        ),
        migrations.RemoveField(
            model_name='historicalseller',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalBuy',
        ),
        migrations.DeleteModel(
            name='HistoricalBuyPlan',
        ),
        migrations.DeleteModel(
            name='HistoricalEquipment',
        ),
        migrations.DeleteModel(
            name='HistoricalEquipmentName',
        ),
        migrations.DeleteModel(
            name='HistoricalGroupSeller',
        ),
        migrations.DeleteModel(
            name='HistoricalNorm',
        ),
        migrations.DeleteModel(
            name='HistoricalNormName',
        ),
        migrations.DeleteModel(
            name='HistoricalPic',
        ),
        migrations.DeleteModel(
            name='HistoricalRent',
        ),
        migrations.DeleteModel(
            name='HistoricalSeller',
        ),
    ]
