# Generated by Django 2.2.2 on 2019-06-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0008_auto_20190605_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyplan',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
