# Generated by Django 2.2.2 on 2019-06-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0009_buyplan_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyplan',
            name='commune',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
