# Generated by Django 2.2.2 on 2019-06-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0010_buyplan_commune'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='catOne',
            new_name='cat_one',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='catTwo',
            new_name='cat_two',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='dateAd',
            new_name='date_ad',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='geoHash',
            new_name='geohash',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='gpsLat',
            new_name='gps_lat',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='gpsLong',
            new_name='gps_long',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='urlOffer',
            new_name='url_offer',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='catOne',
            new_name='cat_one',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='catTwo',
            new_name='cat_two',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='dateAd',
            new_name='date_ad',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='geoHash',
            new_name='geohash',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='gpsLat',
            new_name='gps_lat',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='gpsLong',
            new_name='gps_long',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='urlOffer',
            new_name='url_offer',
        ),
    ]
