# Generated by Django 2.2.2 on 2019-06-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0011_auto_20190608_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='ad_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
