# Generated by Django 2.2.2 on 2019-06-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0012_buy_ad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='commune',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
