# Generated by Django 2.2.2 on 2019-06-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0013_auto_20190609_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
