# Generated by Django 2.2.2 on 2019-06-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0015_buy_pic1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='cat_one',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='cat_two',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
