# Generated by Django 2.1.3 on 2019-01-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("Engine", "0001_initial")]

    operations = [migrations.RemoveField(model_name="token", name="name")]
